resources:
  containers:
  - container: LBPRO
    image: liquibase/liquibase:latest
    options: --user 0:0
trigger:
- master


pool:
  vmImage: ubuntu-latest
container: LBPRO

steps:
- script: |
    cd $(System.DefaultWorkingDirectory)/LiquibaseAzureDevops/Changelogs
    echo  '$(System.DefaultWorkingDirectory)'
    #liquibase --version
    #docker run --rm -v $(System.DefaultWorkingDirectory)/LiquibaseAzureDevops/Changelogs:/liquibase/changelog --defaultsFile=/liquibase/changelog/liquibase.properties update
    #liquibase checks run
    #liquibase tag $(Build.BuildId)
    liquibase --defaultsFile=./liquibase.properties update #--changeLogFile=./dbchangelog.xml
    #liquibase history
  displayName: 'Cloning Repository and Running Liquibase Commands'

- script: |
    mkdir $(System.DefaultWorkingDirectory)/artifacts
    tar -czf $(System.DefaultWorkingDirectory)/artifacts/$(appname)-$(Build.BuildId).tar.gz .
  displayName: 'Creating Artifact'

- upload: $(System.DefaultWorkingDirectory)/artifacts/$(appname)-$(Build.BuildId).tar.gz
  artifact: MyApp
