resources:
  containers:
  - container: LBPRO
    image: liquibase/liquibase:latest
    options: --user 0:0
trigger:
- master

variables:
- group: Liquibase DEV

pool:
  vmImage: ubuntu-latest
container: LBPRO

steps:
- script: |
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    git clone https://github.com/yourusername/yourrepository.git
    cd yourrepository
    liquibase --version
    liquibase checks run
    liquibase tag $(Build.BuildId)
    liquibase update
    liquibase history
  displayName: 'Cloning Repository and Running Liquibase Commands'

- script: |
    mkdir $(System.DefaultWorkingDirectory)/artifacts
    tar -czf $(System.DefaultWorkingDirectory)/artifacts/$(appname)-$(Build.BuildId).tar.gz .
  displayName: 'Creating Artifact'

- upload: $(System.DefaultWorkingDirectory)/artifacts/$(appname)-$(Build.BuildId).tar.gz
  artifact: MyApp
